name: Update gh-pages
on:
  # Trigger on every three hours, or manually.
  schedule:
    - cron: '20 */3 * * *'
  workflow_dispatch:
jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: libssl-dev libkrb5-dev
        version: 1.0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: ./build.sh

    - name: Deploy to gh-pages/
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: out
